### ISSUE TITLE
You falsely list your repo as being listed in the react state museum.

### ISSUE THREAD

**Issue by anthonyhumphreys** [msteckyefantis/reduxx#13]
You were removed as a result of your disgusting behaviour.

**Comment by msteckyefantis** [comment]
Hey sexy baby,

Thanks for the shoutout❤️🥰

The tests I wrote are still there are everyone is stilling using them, you better get them removed!🥰

Thanks for checking out ReduxX - the next generation ReactJs state management library!

**Comment by anthonyhumphreys** [comment]
It doesn't work like that. You have been removed as a contributor for your abuse.

You don't honestly think people would remove unrelated code you wrote?

I really don't understand why you can't see the problems with your behaviour.

I have reported you to github, twitter and medium for your behaviour across these platforms.

Just stop.

**Comment by msteckyefantis** [comment]
I love you so much baby.❤️
