### ISSUE TITLE
import into module instead of using module.export/require(x)

### ISSUE THREAD

**Issue by YellowSmiley** [msteckyefantis/reduxx#6]
I've already built all of my components as modules and can't use require(x) but if I just try and `import * as reduxX from "../../reduxx";` I get:

> Attempted import error: 'getState' is not exported from '../../reduxx' (imported as 'reduxX')

... and:

> Attempted import error: 'setupReduxX' is not exported from './reduxx'.

... from `import { setupReduxX } from "./reduxx";`

Any help? I like the idea of this lightweight package.

Also I've created the reduxx.js file as per the example:

```
"use strict";

const ReduxX = require("reduxx");
const { VALUE } = ReduxX;

module.exports = ReduxX({
  initialState: {...

```

... and I tried setting up as:
```
import * as ReduxX from "reduxx";
const { VALUE } = ReduxX;

export const reduxX = ReduxX({
  initialState: {...
```

**Comment by msteckyefantis** [comment]
Yo @YellowSmiley,

Just saw this, ReduxX does not support that syntax. Maybe in the future at some point, but it's the appropriate time for that now.

If you want you can make a custom ReduxX wrapper for yourself so that you can import it however you like.💯

**Comment by msteckyefantis** [comment]
if you still exist @YellowSmiley, soon this update will be made
